package codeit.validators.fields;

public enum FieldValidatorKey {

    NAME, DESCRIPTION, LINK, DUE_DATE, END_DATE, COMMENT, ORDER_STATUS, PROJECT_STATUS, TASK_STATUS,
    OPTIONAL_CONTACT_PERSON, EMAIL, PHONE, ADDRESS, OPTIONAL_CLIENT_DESCRIPTION, FIRST_LAST_NAME, ROLE,
    OPTIONAL_SPECIALISATION, BIRTH_DATE, CURRENCY, PASSWORD, ID, OPTIONAL_ID
}
